default_install_hook_types: [pre-commit, pre-push]
fail_fast: true

repos:
-   repo: local
    hooks:
    - id: lint
      name: Run Lint
      language: system
      entry: rake swift:lint
      stages: [pre-commit]
      verbose: true
    - id: test
      name: Run Test
      language: system
      entry: rake swift:test
      stages: [pre-push]
      verbose: true
